# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    dir: .
    id: "a2fa"
    main: ./cmd
    binary: a2fa

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - 
    name: a2fa
    folder: Formula
    install: bin.install "a2fa"
    repository:
      owner: csyezheng
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

    commit_author:
      name: Ye Zheng
      email: csyezheng@gmail.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: https://github.com/csyezheng/a2fa

    license: Apache 2.0

    description: A command line tool for generating and validating one-time password

nfpms:
  -
    id: a2fa
    package_name: a2fa
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      
    homepage: https://github.com/csyezheng/a2fa
    vendor: csyezheng
    maintainer: Ye Zheng <csyezheng@gmail.com>
    description: A command line tool for generating and validating one-time password
    license: Apache 2.0

    formats:
      - deb
      - rpm
      
    release: 1
    section: utils
    priority: optional
    bindir: /usr/bin
    
    rpm:
      compression: lzma
